In [1]:
# Bug 잡기 예시

In [2]:
import numpy as np

a = np.random.randn(5)

In [3]:
print(a)

[ 0.3974003   0.9416118  -0.20406048  0.15038093 -0.07039312]


In [4]:
print(a.shape)

(5,)


In [5]:
print(a.T)

[ 0.3974003   0.9416118  -0.20406048  0.15038093 -0.07039312]


In [6]:
print(np.dot(a,a.T))

1.113770070790124


신경망을 코딩하는 경우, 데이터 구조를 사용하는 것이 아니라 a가 5, 1 세로 벡터가 되게끔 하는 것

In [8]:
a = np.random.randn(5, 1)

print(a)

[[-0.27817302]
 [-1.39814041]
 [-1.23720488]
 [ 0.23783807]
 [-1.08491421]]


In [9]:
print(a.T)  # row vector

[[-0.27817302 -1.39814041 -1.23720488  0.23783807 -1.08491421]]


2개의 대괄호

In [11]:
print(np.dot(a, a.T))

[[ 0.07738023  0.38892494  0.34415702 -0.06616014  0.30179386]
 [ 0.38892494  1.9547966   1.72978614 -0.33253102  1.5168624 ]
 [ 0.34415702  1.72978614  1.53067592 -0.29425443  1.34226116]
 [-0.06616014 -0.33253102 -0.29425443  0.05656695 -0.25803391]
 [ 0.30179386  1.5168624   1.34226116 -0.25803391  1.17703885]]


Do not use "rank 1 array"

대신 array를 생성할 때마다, <br>
## a = np.random.randn(5, 1)<br>
이렇게 세로줄 벡터 a.shape = (5, 1)<br>
or <br>
## a = np.random.randn(1, 5)<br>
row vector를 만들 것! a.shape = (1, 5)

"rank 1 array"는 <br> a = a.reshape((5, 1))로 위의 형태로 바꿀 수 있음